### PR TITLE
Full Screen Space background

### PR DESCRIPTION
**Pull request by ariariel**
The smaller rectangle we saw last time is just part of the tetris background. This new image is jut the milky way set at a low alpha as our background for the prototype.

### CODE REVIEW

**Comment by ariariel** [comment]
Why did the travis build fail?

**Comment by ariariel** [comment]
image

UI Tests apparently

**Comment by ariariel** [comment]
just had to run the builds again.. there's some sort of timeout with the UI tests every once in a while. Its the default UITest that comes with Xcode so it can't be our fault.

**Comment by pablitoarango** [comment]
yea i was having that issue with the UITest... I thought i had it solved but i guess not... I'll take a look at it again

**Pull request merged**
